/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homemanagement;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Someone
 */
public class WindowFirst extends javax.swing.JFrame {
    private HelpMethods helpM;          // All program methods in one place (WITHOUT GUI!!!)
    private InformationWindow window2;  // Information Window

    /**
     * Creates new form WindowFirst
     * @param helpM
     */
    public WindowFirst(HelpMethods helpM) {
        initComponents();
        this.helpM = helpM;
        this.setSize(855, 420);
        this.setLocation(300, 200);
        this.setResizable(false);
        StringBuffer pad = new StringBuffer();
        for (int i = 0; i < 100; i++) {
            pad.append(" ");
        }
        this.setTitle(pad + "ניהול משק בית");
        
        this.createImageInMainWindow(); // creating and optimizing the image to fit the jlabel
        
    }
    
    /**
     * Load Main Image.
     */
    public void createImageInMainWindow() {
        BufferedImage img = null; // Read the picture as a BufferedImage
        try {
            img = ImageIO.read(new File("Images/account-manager.jpg"));
            Image dimg = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),Image.SCALE_SMOOTH); // Resize the BufferedImage
            ImageIcon imageIcon = new ImageIcon(dimg); // Create an ImageIcon
            jLabel1.setIcon(imageIcon); // set the image
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to Load Image");
        }
    } // end of method

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFirstWindow = new javax.swing.JPanel();
        LabelTitle = new javax.swing.JLabel();
        ButtonDatabaseInformation = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PanelDatabaseDetails = new javax.swing.JPanel();
        TextFieldPathOfDatabaseFile = new javax.swing.JTextField();
        ButtonCreateDatabase = new javax.swing.JButton();
        ButtonDisconnectDatabase = new javax.swing.JButton();
        ButtonDeleteDatabase = new javax.swing.JButton();
        ButtonLoadDatabase = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFirstWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelFirstWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        LabelTitle.setForeground(new java.awt.Color(0, 102, 255));
        LabelTitle.setText("ניהול משק בית");
        PanelFirstWindow.add(LabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        ButtonDatabaseInformation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonDatabaseInformation.setText("הצג נתונים");
        ButtonDatabaseInformation.setEnabled(false);
        ButtonDatabaseInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDatabaseInformationActionPerformed(evt);
            }
        });
        PanelFirstWindow.add(ButtonDatabaseInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 100, 50));

        ButtonExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonExit.setText("צא");
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });
        PanelFirstWindow.add(ButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 100, 50));

        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("אודות");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelFirstWindow.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 100, 50));

        PanelDatabaseDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "בסיס נתונים", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PanelDatabaseDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextFieldPathOfDatabaseFile.setEditable(false);
        TextFieldPathOfDatabaseFile.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PanelDatabaseDetails.add(TextFieldPathOfDatabaseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 400, 20));

        ButtonCreateDatabase.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonCreateDatabase.setText("צור חדש");
        ButtonCreateDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreateDatabaseActionPerformed(evt);
            }
        });
        PanelDatabaseDetails.add(ButtonCreateDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        ButtonDisconnectDatabase.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonDisconnectDatabase.setText("התנתק");
        ButtonDisconnectDatabase.setEnabled(false);
        ButtonDisconnectDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDisconnectDatabaseActionPerformed(evt);
            }
        });
        PanelDatabaseDetails.add(ButtonDisconnectDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 70, -1));

        ButtonDeleteDatabase.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonDeleteDatabase.setText("מחק קיים");
        ButtonDeleteDatabase.setEnabled(false);
        ButtonDeleteDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteDatabaseActionPerformed(evt);
            }
        });
        PanelDatabaseDetails.add(ButtonDeleteDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        ButtonLoadDatabase.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonLoadDatabase.setText("טען קיים");
        ButtonLoadDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoadDatabaseActionPerformed(evt);
            }
        });
        PanelDatabaseDetails.add(ButtonLoadDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        PanelFirstWindow.add(PanelDatabaseDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 440, 100));
        PanelFirstWindow.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 320, 210));

        getContentPane().add(PanelFirstWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButtonExitActionPerformed

    private void ButtonDatabaseInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDatabaseInformationActionPerformed
        window2 = new InformationWindow(helpM,this); // create information window
        window2.setVisible(true);  // show information window
        this.setVisible(false);  // hide main window
    }//GEN-LAST:event_ButtonDatabaseInformationActionPerformed

    private void ButtonCreateDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateDatabaseActionPerformed
        helpM.createDatabase(this);
        if(this.TextFieldPathOfDatabaseFile.getText().length()>0){
            helpM.SQLiteJDBCDriverConnect(this);
            helpM.SQLiteJDBCDriverCreateNewTable(this);
        }
    }//GEN-LAST:event_ButtonCreateDatabaseActionPerformed

    private void ButtonDeleteDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteDatabaseActionPerformed
        helpM.SQLiteJDBCDriverDisconnect(this); // first, disconnect database file active connection
        helpM.deleteDatabase(this);             // second, delete the file
    }//GEN-LAST:event_ButtonDeleteDatabaseActionPerformed

    private void ButtonDisconnectDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDisconnectDatabaseActionPerformed
        helpM.disconnectDatabase(this);
        if(this.TextFieldPathOfDatabaseFile.getText().length()==0){
            helpM.SQLiteJDBCDriverDisconnect(this);
        }
    }//GEN-LAST:event_ButtonDisconnectDatabaseActionPerformed

    private void ButtonLoadDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoadDatabaseActionPerformed
        helpM.loadDatabase(this);
        if(this.TextFieldPathOfDatabaseFile.getText().length()>0){
            helpM.SQLiteJDBCDriverConnect(this);
        }
    }//GEN-LAST:event_ButtonLoadDatabaseActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(this, "Home Management V1.0\nDeveloper : Dotan T\neMail : dotantz26@gmail.com\nRelease Date : 3/11/2018", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    public JButton getButtonCreateDatabase() {
        return ButtonCreateDatabase;
    }

    public JButton getButtonDatabaseInformation() {
        return ButtonDatabaseInformation;
    }

    public JButton getButtonDeleteDatabase() {
        return ButtonDeleteDatabase;
    }

    public JButton getButtonDisconnectDatabase() {
        return ButtonDisconnectDatabase;
    }

    public JButton getButtonExit() {
        return ButtonExit;
    }

    public JButton getButtonLoadDatabase() {
        return ButtonLoadDatabase;
    }

    public JTextField getTextFieldPathOfDatabaseFile() {
        return TextFieldPathOfDatabaseFile;
    }

    public JButton getjButton3() {
        return jButton3;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCreateDatabase;
    private javax.swing.JButton ButtonDatabaseInformation;
    private javax.swing.JButton ButtonDeleteDatabase;
    private javax.swing.JButton ButtonDisconnectDatabase;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonLoadDatabase;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JPanel PanelDatabaseDetails;
    private javax.swing.JPanel PanelFirstWindow;
    private javax.swing.JTextField TextFieldPathOfDatabaseFile;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
